#!/bin/sh

# Set defaults
export PHPFPM_LISTEN_PORT=${PHPFPM_LISTEN_PORT:-9000}
export PHPFPM_PM_MODE=${PHPFPM_PM_MODE:-dynamic}
export PHPFPM_PM_MAX_CHILDREN=${PHPFPM_PM_MAX_CHILDREN:-4}
export PHPFPM_PM_START_SERVERS=${PHPFPM_PM_START_SERVERS:-1}
export PHPFPM_PM_MIN_SPARE_SERVERS=${PHPFPM_PM_MIN_SPARE_SERVERS:-1}
export PHPFPM_PM_MAX_SPARE_SERVERS=${PHPFPM_PM_MAX_SPARE_SERVERS:-3}
export PHPFPM_PM_MAX_REQUESTS=${PHPFPM_PM_MAX_REQUESTS:-100}
export PHPFPM_OUTPUT_BUFFERING=${PHPFPM_OUTPUT_BUFFERING:-4096}
export PHPFPM_REALPATH_CACHE_SIZE=${PHPFPM_REALPATH_CACHE_SIZE:-800k}
export PHPFPM_REALPATH_CACHE_TTL=${PHPFPM_REALPATH_CACHE_TTL:-86400}
export PHPFPM_MAX_EXECUTION_TIME=${PHPFPM_MAX_EXECUTION_TIME:-90}
export PHPFPM_MAX_INPUT_TIME=${PHPFPM_MAX_INPUT_TIME:-900}
export PHPFPM_MAX_INPUT_VARS=${PHPFPM_MAX_INPUT_VARS:-10000}
export PHPFPM_MEMORY_LIMIT=${PHPFPM_MEMORY_LIMIT:-512M}
export PHPFPM_ERROR_REPORTING=${PHPFPM_ERROR_REPORTING:-'E_ALL & ~E_DEPRECATED'}
export PHPFPM_DISPLAY_ERRORS=${PHPFPM_DISPLAY_ERRORS:-on}
export PHPFPM_LOG_ERRORS=${PHPFPM_LOG_ERRORS:-on}
export PHPFPM_UPLOAD_MAX_FILESIZE=${PHPFPM_UPLOAD_MAX_FILESIZE:-100M}
export PHPFPM_POST_MAX_SIZE=${PHPFPM_POST_MAX_SIZE:-100M}
export PHPFPM_DATE_TIMEZONE=${PHPFPM_DATE_TIMEZONE:-'Etc/UTC'}
export PHPFPM_OPCACHE_ENABLE=${PHPFPM_OPCACHE_ENABLE:-1}
export PHPFPM_OPCACHE_ENABLE_CLI=${PHPFPM_OPCACHE_ENABLE_CLI:-1}
export PHPFPM_OPCACHE_MEMORY_CONSUMPTION=${PHPFPM_OPCACHE_MEMORY_CONSUMPTION:-256}
export PHPFPM_OPCACHE_VALIDATE_TIMESTAMPS=${PHPFPM_OPCACHE_VALIDATE_TIMESTAMPS:-0}
export PHPFPM_FAST_SHUTDOWN=${PHPFPM_FAST_SHUTDOWN:-1}

# Persist variables for other scripts
echo $PHPFPM_LISTEN_PORT > /etc/container_environment/PHPFPM_LISTEN_PORT
echo $PHPFPM_PM_MODE > /etc/container_environment/PHPFPM_PM_MODE
echo $PHPFPM_PM_MAX_CHILDREN > /etc/container_environment/PHPFPM_PM_MAX_CHILDREN
echo $PHPFPM_PM_START_SERVERS > /etc/container_environment/PHPFPM_PM_START_SERVERS
echo $PHPFPM_PM_MIN_SPARE_SERVERS > /etc/container_environment/PHPFPM_PM_MIN_SPARE_SERVERS
echo $PHPFPM_PM_MAX_SPARE_SERVERS > /etc/container_environment/PHPFPM_PM_MAX_SPARE_SERVERS
echo $PHPFPM_PM_MAX_REQUESTS > /etc/container_environment/PHPFPM_PM_MAX_REQUESTS
echo $PHPFPM_OUTPUT_BUFFERING > /etc/container_environment/PHPFPM_OUTPUT_BUFFERING
echo $PHPFPM_REALPATH_CACHE_SIZE > /etc/container_environment/PHPFPM_REALPATH_CACHE_SIZE
echo $PHPFPM_REALPATH_CACHE_TTL > /etc/container_environment/PHPFPM_REALPATH_CACHE_TTL
echo $PHPFPM_MAX_EXECUTION_TIME > /etc/container_environment/PHPFPM_MAX_EXECUTION_TIME
echo $PHPFPM_MAX_INPUT_TIME > /etc/container_environment/PHPFPM_MAX_INPUT_TIME
echo $PHPFPM_MAX_INPUT_VARS > /etc/container_environment/PHPFPM_MAX_INPUT_VARS
echo $PHPFPM_MEMORY_LIMIT > /etc/container_environment/PHPFPM_MEMORY_LIMIT
echo $PHPFPM_ERROR_REPORTING > /etc/container_environment/PHPFPM_ERROR_REPORTING
echo $PHPFPM_DISPLAY_ERRORS > /etc/container_environment/PHPFPM_DISPLAY_ERRORS
echo $PHPFPM_LOG_ERRORS > /etc/container_environment/PHPFPM_LOG_ERRORS
echo $PHPFPM_UPLOAD_MAX_FILESIZE > /etc/container_environment/PHPFPM_UPLOAD_MAX_FILESIZE
echo $PHPFPM_POST_MAX_SIZE > /etc/container_environment/PHPFPM_POST_MAX_SIZE
echo $PHPFPM_DATE_TIMEZONE > /etc/container_environment/PHPFPM_DATE_TIMEZONE
echo $PHPFPM_OPCACHE_ENABLE > /etc/container_environment/PHPFPM_OPCACHE_ENABLE
echo $PHPFPM_OPCACHE_ENABLE_CLI > /etc/container_environment/PHPFPM_OPCACHE_ENABLE_CLI
echo $PHPFPM_OPCACHE_MEMORY_CONSUMPTION > /etc/container_environment/PHPFPM_OPCACHE_MEMORY_CONSUMPTION
echo $PHPFPM_OPCACHE_VALIDATE_TIMESTAMPS > /etc/container_environment/PHPFPM_OPCACHE_VALIDATE_TIMESTAMPS
echo $PHPFPM_FAST_SHUTDOWN > /etc/container_environment/PHPFPM_FAST_SHUTDOWN

# Render configuration files
/usr/local/bin/confd -onetime -backend env
